---
- name: Converge
  hosts: all
  pre_tasks:
    - name:
      yum:
        name:
          - glibc-common
          - coreutils
        state: present

  tasks:
    - name: "Include ansible-role-ohpc-lcc-cenapad"
      include_role:
        name: "ansible-role-ohpc-lcc-cenapad"
      vars:
        openhpc_enable:
          devel: "{{ groups['devnodes'] is defined and (inventory_hostname in groups['devnodes']) }}"
