---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
driver:
  name: podman
platforms:
  - name: nt_sms
    image: localhost/centos/systemd:7.8.2003
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/tmp/ohpc:/tmp/ohpc:z
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
    privileged: false
    tty: True
    pre_build_image: True
    exposed_ports:
      - 53/udp
      - 53/tcp
    published_ports:
      - 0.0.0.0:8053:53/udp
      - 0.0.0.0:8053:53/tcp
    dns_servers:
      - 8.8.8.8
    etc_hosts: {'volpi.lcc.ufmg.br': '150.164.66.69'}
    network: host
    groups:
      - devnodes
provisioner:
  name: ansible
  log: True
  # modifying ansible.cfg
  config_options:
    defaults:
      gathering: smart
      display_skipped_hosts: False
      verbosity: 0
    ssh_connection:
      pipelining: false
  playbooks:
    # create: create.yml
    # prepare: prepare.yml
    converge: converge.yml
    # destroy: destroy.yml
  inventory:
    group_vars:
      all:
        openhpc_release_repo: "http://www.linorg.usp.br/OpenHPC:/Update9/CentOS_7/x86_64/ohpc-release-1.3-2.el7.x86_64.rpm"
        ansible_python_interpreter: "auto_legacy_silent"
    host_vars:
      all:
        openhpc_release_repo: "http://www.linorg.usp.br/OpenHPC:/Update9/CentOS_7/x86_64/ohpc-release-1.3-2.el7.x86_64.rpm"
        ansible_python_interpreter: "auto_legacy_silent"
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
